apiVersion: v1
kind: Service
metadata:
  name: nvulnerable-node-app-service
spec:
  type: LoadBalancer
  selector:
    app: vulnerable-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
