apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulnerable-node-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeliododo/manifest-repo.git
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: vulnerable-node-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true