project: default
source:
  repoURL: https://github.com/zeliododo/manifest-repo.git
  path: staging
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: vulnerable-node-app-staging
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
