apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-node-app
  labels:
    app: vulnerable-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vulnerable-node-app
  template:
    metadata:
      labels:
        app: vulnerable-node-app
    spec:
      containers:
        - name: vulnerable-node-app
          image: your-docker-image:tag
          ports:
            - containerPort: 3000
